### ISSUE TITLE
Opera 10.10 crashes since addition of ES6 class detection

### ISSUE THREAD

**Issue by Xotic750** [inspect-js/is-callable#24]
As per the title. Perhaps test to see if `class` is supported, if not then don't perform the check?

**Comment by ljharb** [comment]
Can you provide more information? It's just doing a regex test on the toString of the function - does stringifying a function work?

**Comment by Xotic750** [comment]
I took a look at it, the `toString` works fine, seems to be a regex/replace (not sure which one of the 3) that it barfs at. Anyway, it dies and you can can get a stack dump and send it as report, but it doesn't give me any clue. I just added an init test to see if `class` was supported and if not then skipped the test. It then worked and I stopped investigating at that point. My guess it is a regex rather than replace, but may be wrong.

**Comment by Xotic750** [comment]
If I get a little spare time I will see if I can narrow down the problem to a specific line under specific conditions (lots of restarts and in a VM), but as I have a fix (described) and being Opera 10.10 (Yuk!), it's low priority for me but I just wanted to make you aware that a problem exists. ;)

**Comment by Xotic750** [comment]
Haven't had much luck in tracking it down, upgraded to 10.63 and still have the same barf. I'm beginning to feel defeated wrt finding the exact combination that causes it.

**Comment by ljharb** [comment]
10.6 doesn't seem to crash, so I'm going to close it - happy to reopen in the future tho if it can be reproduced.
