### ISSUE TITLE
Can't install version 1.1.5

### ISSUE THREAD

**Issue by bobKasbi** [inspect-js/is-callable#49]
When running `npm install is-callable@1.1.5` or `npm install is-callable@latest`, I get following error:

> npm ERR! code ETARGET
npm ERR! notarget No matching version found for is-callable@1.1.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Versions used:

Angular CLI: 8.3.8
Node: 13.7.0
OS: darwin x64
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.803.8 (cli-only)
@angular-devkit/core         8.3.8 (cli-only)
@angular-devkit/schematics   8.3.8 (cli-only)
@schematics/angular          8.3.8 (cli-only)
@schematics/update           0.803.8 (cli-only)

npm version: 6.13.6

Any idea what could cause the issue?

**Comment by ljharb** [comment]
What does `npm config get registry` print out?

**Comment by ljharb** [comment]
Given that the version definitely exists: https://unpkg.com/browse/is-callable@1.1.5/ this seems like you might have a local registry that doesn't have the right data. Closing for now.

**Comment by bobKasbi** [comment]
Yes, that true. `npm config get registry` gives me: `https://nexus.myRepo.xx/repository/npm-all`.
This means, I should update the repo/my local registry before I run `npm install`.
What would be the option to manually install the package via tarball URL?
Example: `npm install https://github.com/ionic-team/ionic-native/tarball/vx.x.x`

**Comment by ljharb** [comment]
`npm install --registry=https://registry.npmjs.org is-callable`?
